apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynetflix
  labels:
    app: myneflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myneflix
  template:
    metadata:
      labels:
        app: myneflix
    spec:
      containers:
      - name: myneflix
        image: docker.io/agus3rdyoga/netflix:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
