apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynetflix
  labels:
    app: mynetflix
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mynetflix
  template:
    metadata:
      labels:
        app: mynetflix
    spec:
      containers:
      - name: mynetflix
        image: ghcr.io/agus-3rd-yoga/mynetflix:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
