name: Docker Image CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mynetflix

jobs:
  lint-dockerfile:
    name: Lint Dockerfile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
          #failure-threshold: error

  build-and-push-image-to-Dockerhub-registries:
    name: Building & pushing image to Docker Hub

    needs: ["lint-dockerfile"]

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@master

    - uses: docker/login-action@master
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@master
      with:
        context: .
        build-args: |
          TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mynetflix:latest

  build-and-push-image-to-Github-registries:

    name: Pushing image to Github registry
      
    needs: ["lint-dockerfile"]

    runs-on: ubuntu-latest
      
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@master
      with:
        ref: 'main'
     
    - uses: docker/login-action@master
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@master
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
    - uses: docker/build-push-action@masterss
      with:
        context: .
        build-args: |
          TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }}
        push: true
        tags: latest
        labels: ${{ steps.meta.outputs.labels }}