name: Docker Image CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  lint-dockerfile:
    name: Lint Dockerfile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: hadolint/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
          #failure-threshold: error

  build-docker-image:
    name: Build & push image to Docker Hub

    needs: ["lint-dockerfile"]

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@master

    - uses: docker/login-action@master
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@master
      with:
        context: .
        build-args: |
          TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }}
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mynetflix:latest
